### PR TITLE
Make index.html responsive and more accessible

### PR DESCRIPTION
**Pull request by cpitclaudel**
The existing index.html page didn't adjust nicely to mobile phones, and there were errors reported by the W3 validator.
Co-authored by @prvshah51 and @fabiomadge .

The contents didn't change, but we changed the markup and the CSS for responsiveness / accessibility.

### CODE REVIEW

**Comment by davidcok** [comment]
Looks fine on my phone, but unnecessarily narrow on a big screen -- and does not adjust to window width changes.
Note that Anjali had a lot to say about the layout(e.g. having the nav links in the top right), so we may want to get her opinion also once this is optimized for both.

**Comment by cpitclaudel** [comment]
> Looks fine on my phone, but unnecessarily narrow on a big screen -- and does not adjust to window width changes.

It adjust to width changes up to 40rem, then it centers the text; this is an accessibility best practice to avoid very long lines.

**Comment by davidcok** [comment]
Fine - but isn't that guideline is about length of text in a line, not about whether there are additional columns with other material.

**Comment by cpitclaudel** [comment]
> but isn't that guideline is about length of text in a line, not about whether there are additional columns with other material.

It is; are you referring to the quick links?  We can float them to the side, if you prefer.  I don't have a strong opinion on this.

**Comment by davidcok** [comment]
Yes please float the Quicklinks to the upper right, at least for the non-mobile version, as that is where Anjali preferred it.
I understand and am fine with the text line length restriction. Thanks for doing these adjustments.

**Comment by cpitclaudel** [comment]
Done; I made two versions (check out the last and before-last commit).  Please let me know which one you prefer.

**Review by davidcok — APPROVED** [review]

**Comment by davidcok** [comment]
Either would be fine. If I have to pick, it would be the later one. I approved it -- merge it if you are happy with it as well.

**Pull request merged**
